[hamburguer.'hamburguer(hamburguer_hamburguer = "hamburguer")']
hamburguer = [
    "-hamburguer",
    "hamburguer-hamburguer=-hamburguer,-hamburguer,hamburguer-hamburguer-hamburguer=16384",
    "-hamburguer",
    "hamburguer-hamburguer=-hamburguer,-hamburguer,hamburguer-hamburguer-hamburguer=16384",
]

[hamburguer.hamburguer86_64-hamburguer-hamburguer]
hamburguer = ["-hamburguer", "hamburguer-hamburguer=-hamburguer-hamburguer-hamburguer=13.0"]
